let DATA=[],OPTIONS={},SCHOOL=null,prediction=null;
const API_BASE=location.port==='8000'?'':'http://127.0.0.1:8000',app=document.querySelector('#app');
const schoolKey=()=>localStorage.getItem('student_records_school');
const api=async(u,o={})=>{o.headers={...(o.headers||{}),...(schoolKey()?{'X-School-ID':schoolKey()}:{})};let r=await fetch(API_BASE+u,o),body=await r.json().catch(()=>({error:r.statusText}));if(!r.ok)throw Error(body.error||'Request failed.');return body};
const opts=a=>(a||[]).map(x=>`<option>${escapeHtml(x)}</option>`).join(''),val=id=>document.querySelector('#'+id)?.value,active=()=>DATA.filter(x=>x.status==='Active');
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const head=(t,s)=>`<div class="page-head"><h1>${t}</h1><p>${s}</p></div>`,kpi=(v,l,c='')=>`<div class="kpi ${c}"><strong>${escapeHtml(v)}</strong><span>${l}</span></div>`,field=(id,l,t='text',v='',x='')=>`<div class="field"><label>${l}</label><input id="${id}" type="${t}" value="${escapeHtml(v)}" ${x}></div>`,badge=x=>`<span class="badge ${String(x).split(' ')[0]}">${escapeHtml(x||'—')}</span>`;
const toast=t=>{let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2500)};

function table(rows,cols,status=false){if(!rows.length)return '<p class="sub">No records yet.</p>';return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c[0]==='risk_level'?badge(r[c[0]]):status&&c[0]==='status'?`<select data-status="${r._id}">${['Pending Approval','Approved','Declined'].map(x=>`<option ${x===r.status?'selected':''}>${x}</option>`).join('')}</select>`:escapeHtml(r[c[0]]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}

function onboarding(){document.querySelector('.product-shell .sidebar').classList.add('setup-sidebar');document.querySelectorAll('[data-page]').forEach(b=>b.disabled=b.dataset.page!=='setup');app.innerHTML=head('Set up your school','Create the private workspace used by the early-warning and student-support system')+`<div class="grid-2 onboarding-grid"><form id="schoolForm" class="card setup-form"><h3>School details</h3>${field('schoolName','School name','text','','required')}<div class="grid-2">${field('schoolCampuses','Campuses','text','Main Campus')}${field('schoolPrograms','Programmes','text','General Programme')}</div><p class="sub">Enter multiple campuses or programmes separated by commas.</p><button class="button">Create workspace and continue</button></form><div class="card solution-summary"><h3>What the system does</h3><ol><li><b>Risk screening</b><span>Scores new applications using the baseline dropout model.</span></li><li><b>Early-warning list</b><span>Orders active student records for staff follow-up.</span></li><li><b>Intervention tracking</b><span>Records calls, meetings, referrals, outcomes and follow-up dates.</span></li><li><b>Student history</b><span>Keeps academic indicators and support actions together.</span></li></ol><p class="sub">Setup only identifies the school that owns the records. It does not replace the early-warning workflow.</p></div></div>`;schoolForm.onsubmit=async e=>{e.preventDefault();let button=e.submitter;button.disabled=true;try{let school=await api('/api/schools',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:val('schoolName'),campuses:val('schoolCampuses').split(','),programs:val('schoolPrograms').split(','),sources:['Website','Walk-In','Referral']})});localStorage.setItem('student_records_school',school.id);await load()}catch(error){toast(error.message)}finally{button.disabled=false}}}

function setup(){app.innerHTML=head('School setup',escapeHtml(SCHOOL.name))+`<div class="grid-2"><div class="card"><h3>Import student records</h3><p class="sub">Upload your school’s CSV. Existing student IDs are updated; new IDs are added.</p><div class="field"><label>CSV file</label><input id="csvFile" type="file" accept=".csv,text/csv"></div><button id="importButton" class="button">Import CSV</button><div id="importResult"></div></div><div class="card"><h3>Required CSV columns</h3><p><code>student_id</code> is required.</p><p class="sub">Recommended: status, program, campus, attendance_rate_pct, grade_average_pct, courses_failed, warnings_issued and at_risk.</p><button id="changeSchool" class="button secondary">Use another school</button></div></div>`;importButton.onclick=importCsv;changeSchool.onclick=()=>{localStorage.removeItem('student_records_school');location.reload()}}
async function importCsv(){let file=csvFile.files[0];if(!file){toast('Choose a CSV file first.');return}let data=new FormData();data.append('file',file);importButton.disabled=true;importResult.innerHTML='<div class="request-status">Importing records…</div>';try{let result=await api('/api/import',{method:'POST',body:data});importResult.innerHTML=`<div class="request-status">${result.imported} records imported.</div>`;await refresh()}catch(error){importResult.innerHTML=`<div class="request-error">${escapeHtml(error.message)}</div>`}finally{importButton.disabled=false}}

function register(){app.innerHTML=head('New student registration','Enter the application details and run the initial risk check')+`<form id="regForm" class="card"><div class="form-grid"><section><h3>Personal details</h3>${field('name','Full name','text','','required')}${field('omang','ID number','text','','required')}${field('age','Age','number','20','min="16" max="80"')}<div class="field"><label>Gender</label><select id="gender">${opts(OPTIONS.gender)}</select></div>${field('phone','Phone number')}</section><section><h3>Programme and campus</h3><div class="field"><label>Campus</label><select id="campus">${opts(OPTIONS.campus)}</select></div><div class="field"><label>Programme</label><select id="program">${opts(OPTIONS.program)}</select></div><div class="field"><label>Enrollment year</label><select id="year">${opts([2025,2026,2027])}</select></div><div class="field"><label>Semester</label><select id="semester">${opts(['Semester 1','Semester 2'])}</select></div><div class="field"><label>Enrollment source</label><select id="source">${opts(OPTIONS.source)}</select></div></section><section><h3>Background</h3>${field('distance','Distance from campus (km)','number','10','min="0" max="500" step="0.5"')}<label class="check"><input id="transport" type="checkbox"> Has own transport</label><div class="field"><label>Parent/guardian education</label><select id="parent">${opts(OPTIONS.parent)}</select></div><label class="check"><input id="financial" type="checkbox"> Applying for financial aid</label><label class="check"><input id="working" type="checkbox"> Working part-time</label></section></div><button class="button">Check registration</button></form><div id="prediction"></div>`;regForm.onsubmit=assess}
async function assess(e){e.preventDefault();let button=e.submitter;button.disabled=true;button.textContent='Checking…';prediction=null;document.querySelector('#prediction').innerHTML='<div class="request-status">Running the enrollment check…</div>';try{let p={age:+val('age'),gender:val('gender'),campus:val('campus'),program:val('program'),year:+val('year'),source:val('source'),parent:val('parent'),distance:+val('distance'),transport:document.querySelector('#transport').checked,financial_aid:document.querySelector('#financial').checked,working:document.querySelector('#working').checked};prediction=await api('/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});let cls=prediction.level.split(' ')[0].toLowerCase(),rec=cls==='low'?'Standard enrollment review.':cls==='medium'?'Enroll with a first-month check-in.':'Escalate to student support before completing enrollment.';document.querySelector('#prediction').innerHTML=`<div class="result ${cls}"><strong>${prediction.level}</strong><p>Baseline estimate: ${prediction.probability.toFixed(0)}%</p></div><div class="card"><h3>Items to review</h3>${prediction.flags.length?prediction.flags.map(x=>`<div class="flag">${escapeHtml(x)}</div>`).join(''):'<p>No enrollment flags.</p>'}<p>${rec}</p><p class="sub">${escapeHtml(prediction.note)}</p><div class="grid-2">${field('officer','Admissions officer')}${field('notes','Notes')}</div><button class="button" id="saveReg">Save application</button></div>`;document.querySelector('#saveReg').onclick=save}catch(error){document.querySelector('#prediction').innerHTML=`<div class="request-error">${escapeHtml(error.message)}</div>`}finally{button.disabled=false;button.textContent='Check registration'}}
async function save(){let b={student_name:val('name'),omang:val('omang'),age:+val('age'),gender:val('gender'),phone:val('phone'),campus:val('campus'),program:val('program'),year:+val('year'),semester:val('semester'),source:val('source'),risk_level:prediction.level,risk_score:prediction.probability.toFixed(0)+'%',officer:val('officer'),notes:val('notes')};await api('/api/registrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});toast('Application saved')}
function risk(){let rows=active().filter(x=>x.at_risk==1||['Critical','High Risk'].includes(x.risk_level)).sort((a,b)=>(b.dropout_probability||0)-(a.dropout_probability||0));app.innerHTML=head('Follow-up list','Active student records requiring staff review')+`<div class="card"><div class="followup-note"><b>Work from the top of the list.</b><span>Critical records should be reviewed today.</span></div>${table(rows,[['student_id','Student'],['program','Programme'],['campus','Campus'],['attendance_rate_pct','Attendance'],['grade_average_pct','Grade'],['courses_failed','Failed'],['risk_level','Priority']])}</div>`}
function intervene(){let ids=active().map(x=>x.student_id).sort();app.innerHTML=head('Record support action','Add a call, meeting, referral or other intervention')+`<form id="intForm" class="card grid-2"><section><div class="field"><label>Student</label><select id="intStudent">${opts(ids)}</select></div><div class="field"><label>Type</label><select id="intType">${opts(['Phone Call','In-Person Meeting','Email Sent','SMS Sent','Parent/Guardian Meeting','Counselor Referral','Tutoring Arranged','Financial Aid Discussion','Academic Warning Issued','Study Plan Created'])}</select></div>${field('staff','Staff member','text','','required')}${field('follow','Follow-up date','date',new Date(Date.now()+604800000).toISOString().slice(0,10))}</section><section><div class="field"><label>Outcome</label><select id="outcome">${opts(['Student responded positively','Student agreed to action plan','No response yet','Student declined support','Parent involved and supportive','Referred to counseling','Issue resolved','Situation unchanged'])}</select></div><div class="field"><label>Notes</label><textarea id="intNotes" rows="7"></textarea></div><button class="button">Save action</button></section></form><div id="history"></div>`;intForm.onsubmit=async e=>{e.preventDefault();await api('/api/interventions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({student_id:val('intStudent'),intervention:val('intType'),staff:val('staff'),follow_up:val('follow'),outcome:val('outcome'),notes:val('intNotes')})});toast('Support action saved');intervene()};api('/api/interventions').then(x=>history.innerHTML=`<div class="card"><h3>Recent actions</h3>${table(x,[['student_id','Student'],['date','Date'],['intervention','Action'],['outcome','Outcome'],['staff','Staff']])}</div>`)}
function record(){if(!DATA.length){app.innerHTML=head('Student search','No student records have been imported yet')+`<div class="card"><p>Open School setup and import a CSV file.</p></div>`;return}app.innerHTML=head('Student search','Open an individual academic and support record')+`<div class="card field"><label>Student</label><select id="studentPick">${opts(DATA.map(x=>x.student_id).sort())}</select></div><div id="record"></div>`;studentPick.onchange=showRecord;showRecord()}
async function showRecord(){let x=DATA.find(s=>s.student_id===val('studentPick')),ints=await api('/api/interventions');document.querySelector('#record').innerHTML=`<div class="kpis">${kpi(x.program,'Programme')}${kpi(x.status,'Status',x.status==='Dropped Out'?'red':'green')}${kpi((x.attendance_rate_pct||0).toFixed(0)+'%','Attendance','orange')}${kpi((x.grade_average_pct||0).toFixed(0)+'%','Grade')}</div><div class="grid-2"><div class="card"><h3>Student details</h3><p><b>Age:</b> ${escapeHtml(x.age)}</p><p><b>Gender:</b> ${escapeHtml(x.gender)}</p><p><b>Campus:</b> ${escapeHtml(x.campus)}</p><p><b>Enrolled:</b> ${escapeHtml(x.year_enrolled)}, ${escapeHtml(x.semester_enrolled)}</p></div><div class="card"><h3>Academic record</h3><p><b>Courses failed:</b> ${escapeHtml(x.courses_failed)}</p><p><b>Warnings:</b> ${escapeHtml(x.warnings_issued)}</p><p><b>Priority:</b> ${badge(x.risk_level)}</p></div></div><div class="card"><h3>Support history</h3>${table(ints.filter(i=>i.student_id===x.student_id),[['date','Date'],['intervention','Action'],['outcome','Outcome'],['staff','Staff']])}</div>`}
async function queue(){let rows=await api('/api/registrations');app.innerHTML=head('Enrollment queue','Applications waiting for a decision')+`<div class="card">${table(rows,[['reg_id','Registration'],['student_name','Student'],['program','Programme'],['campus','Campus'],['risk_level','Review level'],['officer','Officer'],['status','Status']],true)}</div>`;document.querySelectorAll('[data-status]').forEach(s=>s.onchange=async()=>{await api('/api/registrations/'+s.dataset.status,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s.value})});toast('Status updated');await refresh()})}

const views={setup,register,risk,intervene,record,queue};
document.querySelector('.side-nav').insertAdjacentHTML('afterbegin','<button data-page="setup">School setup</button>');
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-page]').forEach(x=>x.classList.remove('active'));b.classList.add('active');views[b.dataset.page]()});
async function refresh(){let x=await api('/api/bootstrap');SCHOOL=x.school;DATA=x.students;OPTIONS=x.options;document.querySelector('.product-shell .brand').textContent=SCHOOL.name;document.querySelector('.product-shell .sidebar').classList.remove('setup-sidebar');document.querySelectorAll('[data-page]').forEach(b=>b.disabled=false)}
async function load(){if(!schoolKey()){onboarding();return}try{await refresh();register()}catch(error){localStorage.removeItem('student_records_school');onboarding()}}
load();
